# Generated by Django 2.1.2 on 2018-10-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_inventario', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='prod',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
