# Generated by Django 2.1.3 on 2018-11-10 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('cred_disponible', models.IntegerField()),
                ('habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Giro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Giro_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mod_clientes.Cliente')),
                ('id_giro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_clientes.Giro')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto_cancelado', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_clientes.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='giros',
            field=models.ManyToManyField(through='mod_clientes.Giro_cliente', to='mod_clientes.Giro'),
        ),
    ]
