# Generated by Django 2.1.3 on 2018-11-06 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_giro',
        ),
        migrations.AddField(
            model_name='cliente',
            name='giros',
            field=models.ManyToManyField(through='mod_clientes.Giro_cliente', to='mod_clientes.Giro'),
        ),
        migrations.AddField(
            model_name='giro_cliente',
            name='id_cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mod_clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='giro_cliente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
