# Generated by Django 2.1.2 on 2018-10-31 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_clientes', '0001_initial'),
        ('mod_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('estado', models.BooleanField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Medio_pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descuento', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_inventario.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('id_cargos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Cargo_venta')),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Cotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Medio_pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_prod_cot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Producto_cotizacion'),
        ),
    ]
