# Generated by Django 2.1.3 on 2018-11-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_inventario', '0001_initial'),
        ('mod_venta_cot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='id_prod_cot',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='productos',
            field=models.ManyToManyField(through='mod_venta_cot.Producto_cotizacion', to='mod_inventario.Producto'),
        ),
        migrations.AddField(
            model_name='producto_cotizacion',
            name='id_cot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Cotizacion'),
        ),
        migrations.AlterField(
            model_name='producto_cotizacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
