# Generated by Django 2.1.3 on 2018-11-06 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mod_venta_cot', '0002_auto_20181106_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_cargos',
        ),
        migrations.AddField(
            model_name='cargo_venta',
            name='id_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cargos',
            field=models.ManyToManyField(through='mod_venta_cot.Cargo_venta', to='mod_venta_cot.Cargo'),
        ),
        migrations.AlterField(
            model_name='cargo_venta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
