# Generated by Django 2.1.3 on 2018-11-10 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_remuneraciones', '0001_initial'),
        ('mod_clientes', '0001_initial'),
        ('mod_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_facturacion.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deuda_pendiente', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medio_pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descuento', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ven_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('comision', models.IntegerField(default=0)),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_inventario.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('tipo', models.CharField(default='Cotizacion', max_length=20)),
                ('cargos', models.ManyToManyField(through='mod_facturacion.Cargo_venta', to='mod_facturacion.Cargo')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_clientes.Cliente')),
                ('id_medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_facturacion.Medio_pago')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Funcionario')),
                ('productos', models.ManyToManyField(through='mod_facturacion.Ven_prod', to='mod_inventario.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='ven_prod',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_facturacion.Venta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_facturacion.Venta'),
        ),
        migrations.AddField(
            model_name='cargo_venta',
            name='id_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mod_facturacion.Venta'),
        ),
    ]
