# Generated by Django 2.1.2 on 2018-10-31 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_venta_cot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vencimiento', models.DateField()),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_venta_cot.Venta')),
            ],
        ),
    ]
