# Generated by Django 2.1.3 on 2018-11-10 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Caja_de_compensacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento_haber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('frecuente', models.BooleanField()),
                ('monto', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=40)),
                ('paterno', models.CharField(max_length=40)),
                ('materno', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('sueldobase', models.IntegerField()),
                ('plansalud', models.IntegerField()),
                ('vendedor', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo_bruto', models.IntegerField()),
                ('total_contabilidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Mutual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('porcentaje_descuento', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Previsionsalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_descuento_haber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('positivo', models.BooleanField()),
                ('tipo', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_prev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Prevision'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_prev_sal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Previsionsalud'),
        ),
        migrations.AddField(
            model_name='descuento_haber',
            name='id_funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Funcionario'),
        ),
        migrations.AddField(
            model_name='descuento_haber',
            name='id_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Tipo_descuento_haber'),
        ),
    ]
