# Generated by Django 2.1.2 on 2018-10-30 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=30)),
                ('frecuente', models.BooleanField()),
                ('historico', models.BooleanField()),
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=12)),
                ('sitio', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Banco')),
                ('id_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=15)),
                ('nombres', models.CharField(max_length=40)),
                ('paterno', models.CharField(max_length=40)),
                ('materno', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Banco')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Horas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('historico', models.BooleanField()),
                ('monto', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo_bruto', models.IntegerField()),
                ('sueldo_liquido', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Descuento')),
                ('id_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Horas')),
            ],
        ),
        migrations.CreateModel(
            name='Mutual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_total', models.IntegerField()),
                ('cuotas', models.IntegerField()),
                ('cuotas_restantes', models.IntegerField()),
                ('historico', models.BooleanField()),
                ('saldo', models.IntegerField()),
                ('valorcuota', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prevision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('porcentaje_descuento', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Previsionsalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('porcentaje_descuento', models.FloatField()),
                ('tipo', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=30)),
                ('frecuente', models.BooleanField()),
                ('historico', models.BooleanField()),
                ('monto', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='id_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Prestamo'),
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='id_salario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Salario'),
        ),
        migrations.AddField(
            model_name='ficha_trabajador',
            name='id_liquidacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Liquidacion'),
        ),
        migrations.AddField(
            model_name='ficha_trabajador',
            name='id_prev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Prevision'),
        ),
        migrations.AddField(
            model_name='ficha_trabajador',
            name='id_prev_sal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Previsionsalud'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_mutual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_remuneraciones.Mutual'),
        ),
    ]
