# Generated by Django 2.1.3 on 2018-11-06 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_clientes', '0002_auto_20181106_1831'),
        ('mod_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subtotal', models.IntegerField()),
                ('impuestos', models.IntegerField()),
                ('descuento', models.FloatField()),
                ('estado', models.BooleanField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_clientes.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Medio_pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descuento', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_cot', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mod_cotizaciones.Cotizacion')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_inventario.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='id_medio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_cotizaciones.Medio_pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='productos',
            field=models.ManyToManyField(through='mod_cotizaciones.Producto_cotizacion', to='mod_inventario.Producto'),
        ),
    ]
